server:
  port: 8093

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

spring:
  config:
    import:
      - optional:file:./.env[.properties]
      - optional:file:../.env[.properties]
  application:
    name: message-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        enabled: false
      config:
        enabled: false
