server:
  port: 8092

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: remark-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        enabled: false
      config:
        enabled: false
