<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.zhixing</groupId>
        <artifactId>zx-learn</artifactId>
        <version>1.0.0</version>
    </parent>
    <artifactId>zx-pay</artifactId>
    <name>zx-pay</name>
    <description>支付服务：支付渠道/支付单/退款单/回调</description>
    <dependencies>
        <dependency>
            <groupId>com.zhixing</groupId>
            <artifactId>zx-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.zhixing</groupId>
            <artifactId>zx-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
    </dependencies>
    <build>
        <finalName>zx-pay</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>com.zhixing.pay.PayApplication</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
